### ISSUE TITLE
`configure_root_logger()` flaky

### ISSUE THREAD

**Issue by dimaqq** [thangbn/json-logging-python#16]
This works:

```
(jlp) … ~/jlp> python
Python 3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import logging
>>> logging.basicConfig()
>>> import json_logging
>>> json_logging.config_root_logger()
>>>
```

But this doesn't:
```
(jlp) … ~/jlp> python
Python 3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import logging
>>> import json_logging
>>> json_logging.ENABLE_JSON_LOGGING = True
>>> json_logging.init()
>>> logging.basicConfig()
>>> json_logging.config_root_logger()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/xxx/site-packages/json_logging/__init__.py", line 84, in config_root_logger
    util.use_cf_logging_formatter(logging.root, JSONLogWebFormatter)
  File "/xxx/site-packages/json_logging/util.py", line 42, in use_cf_logging_formatter
    for logger in loggers_iter:
TypeError: 'RootLogger' object is not iterable
>>>
```

**Comment by thangbn** [comment]
@dimaqq  will take a look

**Comment by thangbn** [comment]
0.0.12 released with the fix
