### ISSUE TITLE
config_root_logger() does not work for non web

### ISSUE THREAD

**Issue by ggtools** [thangbn/json-logging-python#30]
With version 1.0.3, python 3.7 on Mac OS X on a freshly created virtual env.

Simple program:

``` python
import logging
import json_logging

# log is initialized without a web framework name
json_logging.ENABLE_JSON_LOGGING = True
json_logging.init_non_web()

logging.basicConfig(level=logging.DEBUG)

json_logging.config_root_logger()

logger = logging.getLogger("test logger")

logger.info("test log statement")
logger.info("test log statement", extra={'props': {"extra_property": 'extra_value'}})
```

Fails with the following error:

```
Traceback (most recent call last):
  File "root_logger.py", line 10, in <module>
    json_logging.config_root_logger()
  File "/Users/xtof/Documents/Dev/Python/json-logging/venv/lib/python3.7/site-packages/json_logging/__init__.py", line 90, in config_root_logger
    request_logger = _current_framework['app_request_instrumentation_configurator']().get_request_logger()
TypeError: 'NoneType' object is not subscriptable
```

**Comment by thangbn** [comment]
release 1.0.4 to fix this issue
