### ISSUE TITLE
Broken on Python 2.7 due to super()

### ISSUE THREAD

**Issue by mmabreu** [thangbn/json-logging-python#46]
It seems that 1.1.0 is broken on Python 2.7 due to using super() without arguments:

TypeError: super() takes at least 1 argument (0 given)
Logged from file __init__.py, line 57

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/logging/__init__.py", line 868, in emit
    msg = self.format(record)
  File "/usr/local/lib/python2.7/logging/__init__.py", line 741, in format
    return fmt.format(record)
  File "/usr/local/lib/python2.7/site-packages/json_logging/__init__.py", line 228, in format
    log_object = self._format_log_object(record, request_util=_request_util)
  File "/usr/local/lib/python2.7/site-packages/json_logging/__init__.py", line 326, in _format_log_object
    json_log_object = super()._format_log_object(record, request_util)

**Comment by thangbn** [comment]
will take a look

**Comment by thangbn** [comment]
fixed in 1.2.0
